services:
  mysql:
    image: arm64v8/mysql:oracle
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/sql
      - ./mysql-conf/default.cnf:/etc/mysql/my.cnf
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql-server
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpass
    depends_on:
      - mysql

volumes:
  mysql_data:
