import pandas as pd

encoding_mapping_fix = {
    "SERVICIO DE SALUD VAPARA��SO-SAN ANTONIO": "SERVICIO DE SALUD VAPARAÍSO-SAN ANTONIO",
    "SERVICIO DE SALUD AYSEN DEL GENERAL CARLOS IBA��EZ ": "SERVICIO DE SALUD AYSEN DEL GENERAL CARLOS IBAÑEZ ",
    "SERVICIO DE SALUD CONCEPCI��N": "SERVICIO DE SALUD CONCEPCIÓN",
    "SUBSECRETARÍA DE SALUD P��BLICA": "SUBSECRETARÍA DE SALUD PÚBLICA",
    "SERVICIO DE SALUD VI��A DEL MAR Y QUILLOTA": "SERVICIO DE SALUD VIÑA DEL MAR Y QUILLOTA",
    "SERVICIO DE SALUD ARAUCAN��A NORTE": "SERVICIO DE SALUD ARAUCANÍA NORTE",
    "SERVICIO DE SALUD O��HIGGINS": "SERVICIO DE SALUD O´HIGGINS",
    "SERVICIO DE SALUD ��UBLE": "SERVICIO DE SALUD ÑUBLE",
    "SUBSECRETAR��A DE SALUD PÚBLICA": "SUBSECRETARÍA DE SALUD PÚBLICA",
    "SERVICIO DE SALUD CHILO��": "SERVICIO DE SALUD CHILOÉ",
    "INSTITUTO DE SALUD P��BLICA DE CHILE": "INSTITUTO DE SALUD PÚBLICA DE CHILE",
    "CENTRO DE REFERENCIA DE SALUD DE PEÑALOL��N CORDILLERA": "CENTRO DE REFERENCIA DE SALUD DE PEÑALOLÉN CORDILLERA",
    "SERVICIO DE SALUD ARAUCAN��A SUR": "SERVICIO DE SALUD ARAUCANÍA SUR",
}

df = pd.read_csv(
    "../../datasets/pagos_salud_2018-2024.csv",
    delimiter=",",
    converters={
        "nombre_capitulo": lambda value: encoding_mapping_fix.get(value, value)
    },
    encoding="utf-8",
    on_bad_lines="warn",
    dtype={
        "periodo": "int",
        "mes": "int",
        "partida": "str",
        "nombre_partida": "str",
        "capitulo": "str",
        "nombre_capitulo": "str",
        "area": "str",
        "nombre_area": "str",
        "subtitulo": "str",
        "nombre_subtitulo": "str",
        "beneficiario": "str",
        "nombre_beneficiario": "str",
        "numero_documento": "str",
        "fecha_documento": "str",
        "tipo_documento": "str",
        "orden_de_compra": "str",
        "fecha_ingreso": "str",
        "fecha_recepcion_conforme": "str",
        "fecha_pago": "str",
        "moneda": "str",
        "monto_original": "int",
        "monto": "int",
        "devengo_original": "int",
        "devengo": "int",
        "honorario": "str",
        "proveedor": "str",
        "sector": "str",
        "region": "str",
        "agregado": "int",
        "persona": "str",
        "intraestado": "str",
        "bloqueo_oc": "int",
        "item": "str",
        "nombre_item": "str",
        "asignacion": "str",
        "nombre_asignacion": "str",
        "codigo_bip": "str",
        "nombre_bip": "str",
        "codigo_ubicacion_geografica": "str",
        "nombre_ubicacion_geografica": "str",
        "codigo_programa_presupuestario": "str",
        "nombre_programa_presupuestario": "str",
        "dias_de_pago": "str",
        "dias_de_pago_cat": "str",
        "deuda_flotante": "str",
    },
    parse_dates=[
        "fecha_documento",
        "fecha_ingreso",
        "fecha_recepcion_conforme",
        "fecha_pago",
    ],
    date_format="%d-%m-%Y",
).rename(columns={"periodo": "año"})
